name: Job Watcher

on:
  schedule:
    - cron: "30 7 * * *"   # every day at 07:30 UTC ≈ 1:00 PM IST
  workflow_dispatch:        # allows manual run

jobs:
  run-job-watcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job watcher
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python job_watcher.py

